---
- hosts: remoteservers
  become: yes
  gather_facts: no
  tasks:

   - name: Add group "docker" to remote server
     group:
       name: docker
       gid: 2010
       state: present

   - name: Add group "k8s" to remote server
     group:
       name: k8s
       gid: 2015
       state: present

   - name: Add group "Guest" to remote server
     group:
       name: guest
       gid: 2016
       state: present

   - name: Add user "sysadmin" to remote server
     user:
       name: sysadmin
       comment: "Privileged User"
       uid: 2001
       group: docker
       groups: k8s,sudo
       append: yes
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "Pendaflex" to remote server
     user:
       name: pendaflex
       comment: "Accountant UnPrivileged User"
       uid: 2002
       group: docker
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "kinjerez" to remote server
     user:
       name: 'kinjerez'
       comment: "Kubernettes Admin Privileged User"
       uid: 2003
       group: k8s
       groups: docker,sudo
       append: yes
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "Guest001" to remote server
     user:
       name: guest001
       comment: "Temp account"
       uid: 2004
       group: guest
       shell: /bin/bash
       createhome: no
       password: ''
       expires: 1525198731

   - name: Force user "Guest001" to change the password
     command: 
         chage -d 0 guest001

   - name: Remove user "Talakawa" from remote server
     user:
       name: talakawa
       state: absent
       remove: yes
...
