---
- name: Install Docker and Docker Compose
  hosts: all #change this
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Add current user to docker group
      user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: yes

    - name: Download Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker Compose is executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'
    
  environment:
    DOCKER_CLI_APT_REPOSITORY: "https://download.docker.com/linux/ubuntu"
    DOCKER_CLI_APT_SOURCE: "https://download.docker.com/linux/ubuntu"
  
  vars:
    ansible_distribution_release: "{{ ansible_distribution_release | lower }}"
  
  tasks:
    - name: Install Docker CLI
      apt:
        name: docker-ce-cli
        state: present
