---
- hosts: all
  vars:
    ansible_host_key_checking: false ##If you get an error about hosts not trusted
  become: false
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes